<a href="https://colab.research.google.com/github/valmirf/processamento_imagens/blob/master/Introdu%C3%A7%C3%A3o/aula_01_python_introducao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone https://github.com/valmirf/processamento_imagens.git

# Introdução ao Python

## 1. Variáveis

Um nome que é usado para denotar algo ou um valor é chamado de variável. No python, variáveis ​​podem ser declaradas e valores podem ser atribuídos a ela da seguinte maneira,

In [ ]:
x = 2
y = 5.2
xy = 'Hey'
print(type(x), type(y),type(xy))

In [ ]:
print(x+y, xy)

Múltiplas variáveis podem ser atribuídas com o mesmo valor.

In [ ]:
x , y = 1,2
print(x, y)

## 2. Operadores

### 2.1 Operadores Aritméticos

In [ ]:
1+2 #adição

In [ ]:
2-3 #subtração

In [ ]:
2*5 #Multiplicação

In [ ]:
10/3 #divisão

In [ ]:
10//3 #Divisão inteira

In [ ]:
10%7 #modulo

In [ ]:
4**(1/2) #Potencia

### 2.2 Operadores Relacionais

In [ ]:
Z = 1
Z == 1 #Igual a

In [ ]:
Z != 1 #Diferente de

In [ ]:
Z < 0 #Menor que

In [ ]:
Z > 0 #Maior que

In [ ]:
Z <= 1 #Menor ou igual a 

In [ ]:
Z >= 1 #Maior ou igual a

## 3. Tipos de dados básicos

### 3.1 Números

inteiros e flutuantes funcionam como você esperaria de outras linguagens:

In [ ]:
x = 3
print(x, type(x))

In [ ]:
print(x + 1)   # Addition;
print(x - 1)   # Subtraction;
print(x * 2)   # Multiplication;
print(x ** 2)  # Exponentiation;

In [ ]:
x += 1
print(x)  # Prints "4"
x *= 2
print(x)  # Prints "8"

Obs.: O Python não possui operadores de incremento unário (x ++) ou decremento (x--).

### 3.2 Boleano

O Python implementa todos os operadores usuais da lógica booleana, mas usa palavras inglesas em vez de símbolos (&&, ||, etc.):

In [ ]:
t, f = True, False
print(type(t)) # Prints "<type 'bool'>"

Operações

In [ ]:
print(t and f) # Logical AND;
print(t or f)  # Logical OR;
print(not t)   # Logical NOT;
print(t != f)  # Logical XOR;

### 3.3 String

In [ ]:
hello = 'hello'   # String literals can use single quotes
world = "world"   # or double quotes; it does not matter.
print(hello, len(hello))
print(hello[0:4])

## 4. Estrutura de dados

### 4.1 Listas

In [ ]:
xs = [3, 1, 2]   # Create a list
print(xs, xs[2])
print(xs[-1])     # Negative indices count from the end of the list; prints "2"

In [ ]:
print(len(xs)) #número de elementos na lista

In [ ]:
xs[2] = 'foo'    # Lists can contain elements of different types
print(xs)

In [ ]:
xs.append('bar') # Add a new element to the end of the list
print(xs)  

In [ ]:
x = xs.pop()     # Remove and return the last element of the list
print(x, xs )

In [ ]:
lista1 = [1,3,5,6,5,4,3]
print(sum(lista1))

In [ ]:
lista1.remove(3) #remove a primeira ocorrência da lista
print(lista1)

In [ ]:
print(lista1.count(5)) #Retorna o número de ocorrência

In [ ]:
4 in lista1

In [ ]:
lista1.clear()  #remove todos os elementos da lista

### 4.2 Dicionários

In [ ]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in d)     # Check if a dictionary has a given key; prints "True"

### 4.3 Tuplas

Uma tupla é uma lista ordenada (imutável) de valores. Uma tupla é, em muitos aspectos, semelhante a uma lista; Uma das diferenças mais importantes é que as tuplas podem ser usadas como chaves em dicionários e como elementos de conjuntos, enquanto as listas não podem. Aqui está um exemplo trivial:

In [ ]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
t = (5, 6)       # Create a tuple
print(type(t))
print(d[t]) 
print(d[(1, 2)])

In [ ]:
e = 4
t = (1,2,e)

## 5. Estruturas de condição e repetição

### 5.1 If e else

In [ ]:
a, b = 1, 2
if a > b:
    print(str(a)+' é maior que '+str(b))
elif a < b:
    print(str(a)+' é menor que '+str(b))
else:
    print(str(a)+' é igual a '+str(b))

### 5.2 Loops

In [ ]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

In [ ]:
print(list(range(3)))#retorna uma série numérica no intervalo enviado como argumento.
print(list(range(3,5)))

In [ ]:
for i in range(len(animals)):
    print(i, animals[i])

In [ ]:
conta = 8
while(conta <= 10):
    print(conta)
    conta+=1

## 6. Funções

In [ ]:
def hello(name, loud=False):
    if loud:
        print('HELLO, %s' % name.upper())
    else:
        #print('Hello, %s!' % name)
        return 'Hello, %s!' % name

hello('Bob')
hello('Fred', loud=True)

## 7. Numpy

Numpy é a biblioteca central para computação científica em Python. Ele fornece um objeto de matriz multidimensional de alto desempenho e ferramentas para trabalhar com essas matrizes.
Para usar o Numpy, primeiro precisamos importar o pacote numpy:

In [ ]:
import numpy as np

### 7.1 Arrays

In [ ]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)  

In [ ]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

In [ ]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

In [ ]:
b = np.ones((3,2))   # Create an array of all ones
print(b)

In [ ]:
c = np.full((2,2), 7) # Create a constant array
print(c) 

In [ ]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

In [ ]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

In [ ]:
f = np.arange(3)
g = np.arange(3,7)
print(f)
print(g)

### 7.2 Datatypes

Cada matriz numpy é uma grade de elementos do mesmo tipo. Numpy fornece um grande conjunto de tipos de dados numéricos que você pode usar para construir matrizes. Numpy tenta adivinhar um tipo de dados quando você cria uma matriz, mas funções que constroem matrizes geralmente também incluem um argumento opcional para especificar explicitamente o tipo de dados. Aqui está um exemplo:

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype
w = np.array([1, 2], dtype=np.uint8)
print(x.dtype, y.dtype, z.dtype, w.dtype)

### 7.3 Soma

In [ ]:
y = np.array([1,2,3])
x = np.array([[1,2],[3,4]])
print(np.sum(y))
print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

## 8. Matplotlib

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
 

# Compute the x and y coordinates for points on a sine curve
x = np.arange(0, 3 * np.pi, 0.1)
y = np.sin(x)

# Plot the points using matplotlib
plt.plot(x, y)

## 9. Opencv

In [ ]:
import cv2 # OpenCV-Python

### 9.1 Lendo e escrevendo imagens

In [ ]:
img = cv2.imread('processamento_imagens/imagens/varig747.jpg') #Lendo uma imagem
print(img.shape)

plt.figure(figsize=(6, 6), dpi= 80, facecolor='w', edgecolor='k')
plt.axis("off")
imgColor = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) #Conversão necessária para protar a imagem, devido ao opencv usa o 
                                                 #formato RGB, enquanto o matplotlib usa BGR
plt.imshow(imgColor)  


In [ ]:
varig_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print(varig_gray.shape)
plt.imshow(varig_gray, cmap='gray') 

cv2.imwrite('varig_gray.jpg', varig_gray) #salva uma imagem no caminho especificado

*italicized text*### 9.2 Histograma da imagem

### 9.2 Algumas coisas úteis

# #### 9.2.1 Criando uma imagem com numpy

In [ ]:
# Create a black image
img2 = np.zeros((512,512,3), np.uint8)
plt.imshow(img2)

In [ ]:
print(img2.shape)
img2[:200, :200] = [255,0,160]
img3 = cv2.cvtColor(img2, cv2.COLOR_BGR2RGB)
plt.imshow(img3)

#### 9.2.2 Separando Canais

OBS.: Para unir novamente os canais use "img = cv2.merge((b,g,r))"

In [ ]:
b, g, r = cv2.split(imgColor)
fig, axes = plt.subplots(1, 3, figsize=(10, 5))
ax = axes.ravel()

ax[0].imshow(r, cmap='Reds')
ax[0].set_title('R')
ax[0].set_axis_off()

ax[1].imshow(g, cmap='Greens')
ax[1].set_title('G')
ax[1].set_axis_off()

ax[2].imshow(b, cmap='Blues')
ax[2].set_title('B')
ax[2].set_axis_off()